services:
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=America/Bogota
      - SUBDOMAINS=alansoft
      - TOKEN=${DUCKDNS_TOKEN}
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'America/Bogota'
      WEBPASSWORD: 'admin'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      pihole_net:
        ipv4_address: 192.168.1.150
  
  wireguard:
    image: linuxserver/wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - SERVERURL=alansoft.duckdns.org
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=192.168.1.185
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./config:/config 
    ports:
      - "51820:51820/udp" 
    cap_add:
      - NET_ADMIN 
    restart: unless-stopped

networks:
  pihole_net:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
